Feature/login
OZ-Coding-School/oz_03_collabo-003-BE pull request #36
Opened 2024-08-26 06:37 UTC by siangit

### 📑 닉네임 중복 & 사업자 등록 확인

* **[기능 추가]**  
닉네임 중복 & 사업자 등록 확인 기능 추가
* **세부 내용:**  
프론트 요청에 의해 닉네임 중복 확인
공공 데이터 포털 오픈 api를 사용해서 사업자 등록이 되어있는지 확인

## 📝 PR 설명:

**✨ 변경 사항:**

```
    * 로그인 페이지 UI 디자인 개선
    * 로그인 입력 폼 유효성 검사 추가
```
*

**🤔 이유:**

```
    * 사용자 편의성 향상 및 로그인 오류 감소
    * API 응답 데이터 불일치 문제 해결
```
*

**💥 영향:**

```
    * 로그인 페이지 관련 CSS 파일 수정
    * `User` 모델 필드 추가
```
*

**🧪 테스트:**

```
    * 데스크톱 및 모바일 환경에서 로그인 기능 정상 작동 확인
    * 수정된 API 엔드포인트 테스트 결과 성공
```
*

**🔗 참고 자료:**
```
    * #123 로그인 페이지 UI 개선 요청
```
*

**📸 스크린샷 / 영상:** (선택 사항)

* 변경 사항을 시각적으로 보여줄 수 있는 스크린샷 또는 영상 첨부
    * [스크린샷 링크]
    * [영상 링크]

2024-08-26 09:00 UTC, ChoiWheatley commented
main 브랜치로 PR을 보냈습니다. develop 브랜치로 PR을 등록해주세요.

2024-08-27 07:53 UTC, ChoiWheatley requested changes
비밀키가 노출되어 있다는 점 빼면 바로 develop 브랜치로 병합해도 좋을 것 같습니다. 확인 후 커밋 부탁드릴게요!

2024-08-27 07:53 UTC, ChoiWheatley commented on allthe/accounts/views.py
> +            service_key = "81v1ccEVwCErTew95hfnA%2Br95pix3CQCzdfoXag6gg34TJeXJIawjx%2FGgYYeYrL6dTMt0DFvYKvIpAr8h3p35Q%3D%3D"
비밀키가 노출이 되어있습니다. .env로 키를 숨겨주세요

2024-08-28 06:17 UTC, LSY310 approved these changes
굳구입니다

2024-08-28 06:20 UTC, ChoiWheatley approved these changes
LGTM

2024-08-28 06:20 UTC, merged